### ISSUE TITLE
requirement.txt file is missing

### ISSUE THREAD

**Issue by robinsdeepak** [peri044/STT#1]
Will you please requirement.txt file to the repository as i'm getting a lots of error because of different versions of the modules.

**Comment by zhengqibin** [comment]
> Will you please requirement.txt file to the repository as i'm getting a lots of error because of different versions of the modules.

How can you generate the TF-Record? Some files seem to be missing to run data.coco_data_loader.py

**Comment by peri044** [comment]
I've just uploaded the script to generate text files which contain paraphrases. You can find it here (https://github.com/peri044/STT/blob/master/prepare_mscoco_pairs.py). I haven't had the time to clean up the code. 

prepare_mscoco_pairs.py should generate the paraphrases in text files and the coco_data_loader.py should read them and generate TF records accordingly. You need to modify the data paths according to your MSCOCO data location.  Also, the code should be compatible with versions > TF 1.11. I don't have the system that I ran to check the versions of other modules but I believe it should be fairly easy to fix/port to other versions.

**Comment by arunikayadav42** [comment]
Hi! in prepare_mscoco_pairs.py what is captions file? Is it the captions_train2014.json or instances_train2014? And also the captions['sentences'] field?
