### ISSUE TITLE
Preprocessed Dataset

### ISSUE THREAD

**Issue by arunikayadav42** [peri044/STT#2]
Hi! Please let me know from where to download the preprocessed dataset because I cannot find the sentences_train2014.json file and also the train.npy file

**Comment by peri044** [comment]
Hey, I think we probably had an older version of the dataset. I've updated the prepare_mscoco_pairs.py script to use captions_train2014.json. `train.npy` file used to have the pre-computed features of all the 10 crops of mscoco images (obtained from one of the Karpathy's repos which should be publicly available).

**Comment by arunikayadav42** [comment]
Thanks a tonne for the update ! I will check and let you know. Actually I am trying to regenerate your results to work on multi-tasking. Any help given will be of great value.
