### ISSUE TITLE
tensorflow.python.framework.errors_impl.InvalidArgumentError: Input to DecodeRaw has length 220287 that is not a multiple of 4, the size of float

### ISSUE THREAD

**Issue by arunikayadav42** [peri044/STT#3]
I get this error when running train_coco.sh script. I ran the coco_data_loader.py and obtained the tensorflow records.

**Comment by peri044** [comment]
This can be due to the wrong TF records file. As I see in the `train_coco.sh` script, the default model used is `stt-att`. For this model, a TF record sample should have (36, 2048) feature for 1 image and two paraphrases. I would start with checking the shape of the image when you're writing TF records. Let me know if that doesn't help.

**Comment by arunikayadav42** [comment]
So do I resize my images to 36*2048 ?

**Comment by arunikayadav42** [comment]
Also if the default model is stt-att, how does it dffer from other model-types. The images are not getting reshaped to the necessary size as I understand. So do you suggest making changes to the train_stt.py python script so that the TF record stores the reshaped image features?

**Comment by peri044** [comment]
No. (36 x2048) is the size of the feature map for one image. These are precomputed features obtained from SCAN paper. Please refer to my paper attached in the README for more details. 
Some background on this : 
SCAN paper takes an image as input and extracts 36 proposals using Faster RCNN from the image. These proposals are passed through resnet and each proposal will have a feature map of size 2048. So 36 proposals for 1 image gives a feature map of size 36x2048. You can download these features directly from SCAN paper repo https://github.com/kuanghuei/SCAN#download-data

**Comment by arunikayadav42** [comment]
Thanks again ! I will try them out

**Comment by arunikayadav42** [comment]
Also , there is no mention of using the script extract_image_features in the readme, so do we run that because in the paper it does say to extract image features before training

**Comment by arunikayadav42** [comment]
> No. (36 x2048) is the size of the feature map for one image. These are precomputed features obtained from SCAN paper. Please refer to my paper attached in the README for more details.
> Some background on this :
> SCAN paper takes an image as input and extracts 36 proposals using Faster RCNN from the image. These proposals are passed through resnet and each proposal will have a feature map of size 2048. So 36 proposals for 1 image gives a feature map of size 36x2048. You can download these features directly from SCAN paper repo https://github.com/kuanghuei/SCAN#download-data

But should there not be some fixed input size for feeding images into Faster RCNN

**Comment by arunikayadav42** [comment]
> No. (36 x2048) is the size of the feature map for one image. These are precomputed features obtained from SCAN paper. Please refer to my paper attached in the README for more details.
> Some background on this :
> SCAN paper takes an image as input and extracts 36 proposals using Faster RCNN from the image. These proposals are passed through resnet and each proposal will have a feature map of size 2048. So 36 proposals for 1 image gives a feature map of size 36x2048. You can download these features directly from SCAN paper repo https://github.com/kuanghuei/SCAN#download-data

After downloading the pretrained features and running the command 
`python -m data.coco_data_loader --precompute \
                                --record_path para_att_pred.tfrecord \
                                --feature_path coco_precomp/testall_ims.npy \
                                --captions_path <path_to_coco_captions>`
what argument do we pass for the --feature_path? Please let me know.

**Comment by arunikayadav42** [comment]
And do I need to make changes in the coco_data_loader.py script to read the precomputed image features?

**Comment by peri044** [comment]
Yes. You do need to make changes to it. Most of it is already there and the changes required might be setting up with right paths and the data format.

**Comment by arunikayadav42** [comment]
The changes regarding the right paths are fine but regarding using the SCAN dataset image features we need to set the precompute flag to True and use the testall_ims.npy features , right? I did that but still the image size mismatch error remains.

**Comment by peri044** [comment]
Yes precompute should be set to true, use training features for train tfrecord, and verify if the shapes of the image features before you're writing in the TF record. (https://github.com/peri044/STT/blob/master/data/coco_data_loader.py#L106) features[im_idx] should be of data type tf.float32 (decoded in that type https://github.com/peri044/STT/blob/master/data/coco_data_loader.py#L141)  and shape (36, 2048)

**Comment by arunikayadav42** [comment]
> Yes precompute should be set to true, use training features for train tfrecord, and verify if the shapes of the image features before you're writing in the TF record. (https://github.com/peri044/STT/blob/master/data/coco_data_loader.py#L106) features[im_idx] should be of data type tf.float32 (decoded in that type https://github.com/peri044/STT/blob/master/data/coco_data_loader.py#L141) and shape (36, 2048)

Also the testall_ims.npy has features for only 5000 images, right? So what do we do to train with train_ims.npy? As the file is too large and the program refuses to read that

**Comment by arunikayadav42** [comment]
![error](https://user-images.githubusercontent.com/28708494/69511520-74dddf80-0f66-11ea-9ce0-aadaf01dd76b.png)
Hi even after having got the precomputed weights, I still am able to remove the invalid input size error

Error: tensorflow.python.framework.errors_impl.InvalidArgumentError: Input to reshape is a tensor with 294912 values, but the requested shape has 73728
         [[{{node Reshape}}]]
         [[IteratorGetNext]]

**Comment by peri044** [comment]
Is your error coming from this line ? (can't see it from stack trace) https://github.com/peri044/STT/blob/master/data/coco_data_loader.py#L176

1) 73728 is basically 36 x 2048 which should be the feature map size when you're using `stt-att` model.
2) 294912  is coming from your tf records (I'm not sure what it is). Please check what you're writing into TF records. (Code line: https://github.com/peri044/STT/blob/master/data/coco_data_loader.py#L56). `image_path` should be an array (feature map) of size 36x2048. Verify the shapes. Something might be going wrong here for you.

**Comment by arunikayadav42** [comment]
I changed this function 
https://github.com/peri044/STT/blob/e1fcab718143888611c5186c52df56dc18de795d/data/coco_data_loader.py#L22

as it was raising an error by not accepting the str(value) so I encoded that using

value = value.encode()

and to inspect the tfrecord file , can we inspect it by reading it again because i have checked the code that's writing into the file and size of the image seems fine.

**Comment by arunikayadav42** [comment]
I verified the shape of the image_path and it is 36*2048 but when i run your original code 

https://github.com/peri044/STT/blob/e1fcab718143888611c5186c52df56dc18de795d/data/coco_data_loader.py#L24

this line gives me error so i have to change the code to :
`def _bytes_feature(self, value):
        """Wrapper for inserting a bytes Feature into a SequenceExample proto."""
        # print(value)
        if isinstance(value, str) :
            value = value.encode()
            print("Decoded: ")
            # print(value.decode())
        # print(type(value))
        return tf.train.Feature(bytes_list=tf.train.BytesList(value=[value]))`

Only this could possibly give an error but i cannot figure out. How did it work for you?Please let me know.

**Comment by arunikayadav42** [comment]
`def _bytes_feature(self, value):
        """Wrapper for inserting a bytes Feature into a SequenceExample proto."""
        # print(value)
        if isinstance(value, str) :
            value = value.encode()
            print("Decoded: ")
            # print(value.decode())
        # print(type(value))
        return tf.train.Feature(bytes_list=tf.train.BytesList(value=[value]))`

**Comment by arunikayadav42** [comment]
Its working thanks a lot for all the help :)
