### ISSUE TITLE
eval_coco.sh parameters 

### ISSUE THREAD

**Issue by arunikayadav42** [peri044/STT#4]
Please let me know how are we going to select the 5000 images for the validation using eval_coco.sh.

**Comment by arunikayadav42** [comment]
![error_1](https://user-images.githubusercontent.com/28708494/70199271-48308180-1737-11ea-9d11-1714834e9d22.png)
I tried to run the evaluation script but it gives me the above error.Please let me know how to deal with it if you have any idea

**Comment by arunikayadav42** [comment]
There is an error in the eval_gpu.py script it calls the build_stt_model instead of the build_stt_attention_model

**Comment by arunikayadav42** [comment]
Hi! Your evaluation code for coco dataset is not complete. Would you please share the code here?Thanks

**Comment by peri044** [comment]
There are two eval scripts eval_gpu.py and eval_bi.py. As far as I remember eval_bi.py should be used for stt-att model and the eval_gpu.py for the base model. Can you try both of them to see which one works for you ?

**Comment by arunikayadav42** [comment]
How do we generate the tf records for validation @peri044 ?
